spring.application.name=Amazori

# RapidAPI Configuration
amazon.api.key=d482c077b7mshba0efc62dfde5eep1884eajsn5d02c2b14ba9
amazon.api.host=real-time-amazon-data.p.rapidapi.com

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:55701/amazori_db
spring.datasource.username=amazori_user
spring.datasource.password=amazori_password

# JPA & Hibernate Settings
# update - updates the schema automatically based on your Java classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true